name: Test and Deploy

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main

jobs:
  # Primer job: Pruebas
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm' 

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

  # Segundo job: Despliegue
  deploy:
    runs-on: windows-latest
    needs: test  # Se ejecutará después de que finalice el job de pruebas
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'  # Solo en push a main

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm ci

      - name: Run deploy
        run: npm run deploy